.TH CHKCRONTAB 1 "" "" "Utilities"
.SH NAME
chkcrontab \- Crontab lint tool

.SH SYNOPSIS
.sp
\fBchkcrontab\fP <\fIfile\fP or \fB\-\fP>

.SH DESCRIPTION
.sp
The \fBchkcrontab\fP command provides a command line tool to check the
correctness of system crontab files like \fB/etc/crontab\fP or the
files in \fB/etc/cron.d\fP.
.sp
If the given filename is \fB\-\fP data is read from stdin.
.sp
The following check are run against the given crontab file.
.IP \(bu 2
File name is a valid cron file name (skipped if read from stdin).
.IP \(bu 2
File is not group or world writable (skipped if read from stdin).
.IP \(bu 2
Variable assignments do not have \fB$\fP\(aqs in right hand side.
.IP \(bu 2
Confirms that \fB@\fP specifiers are valid.
.IP \(bu 2
Confirms that users exist on the system (or NIS or LDAP).
.IP \(bu 2
Validates the basic syntax of cron job lines.
.IP \(bu 2
Validates that each time field is within limits.
.IP \(bu 2
Checks that ranges and sequences are not used for the "day of
week" and "month" fields.
.IP \(bu 2
Reports any bare \fB%\fP in a command.
.SH EXAMPLES
\fBchkcrontab /etc/cron.d/certbot\fP
.sp
\fBcrontab -l | chkcrontab -u -\fP
.SH RESOURCES
.sp
Project website: \fI\%https://github.com/wummel/chkcrontab\fP
.SH COPYING
.sp
Copyright (C) 2012 Kevin Lyda.
Licensed under the Apache License, Version 2.0
.SH AUTHOR
Kevin Lyda <lyda@google.com>
